Bump cypress from 4.12.1 to 5.0.0 (#64)
* Bump cypress from 4.12.1 to 5.0.0

Bumps [cypress](https://github.com/cypress-io/cypress) from 4.12.1 to 5.0.0.
- [Release notes](https://github.com/cypress-io/cypress/releases)
- [Commits](https://github.com/cypress-io/cypress/compare/v4.12.1...v5.0.0)

Signed-off-by: dependabot[bot] <support@github.com>

* Update build.yml

* Update cypress.yml

* Update cypress.yml

* Update cypress.yml

* Update package.json

* Update package.json

* Update cypress.yml

* Update build.yml

* Update cypress.yml

* Update cypress.yml

* Update package.json

* Update cypress.yml

* Update server.js

* Delete cypress.env.json

* Delete _config.yml

* Update cypress.json

* Delete .env

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: jsbase <andre.siedersleben@gmail.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,62 +1,120 @@
 ---
-name: build
+name: Build runner
 
 on:
-  pull_request:
-    paths-ignore:
-      - "**.md"
+  # pull_request:
+    # branches:
+      # - master
+      # - releases/**
+    # paths-ignore:
+      # - "**.md"
+
   push:
+    branches:
+      - master
+      - releases/**
     paths-ignore:
       - "**.md"
 
 jobs:
   build:
     runs-on: ${{ matrix.os }}
-    continue-on-error: false # prevents a workflow run from failing when a job fails
-    timeout-minutes: 12
+    continue-on-error: false # prevents workflows from running when a job fails
+    timeout-minutes: 20
 
     strategy:
-      fail-fast: true # github will cancel all in-progress jobs if any matrix job fails
+      fail-fast: true # cancel all in-progress jobs if any matrix job fails
       matrix:
         os: [ubuntu-20.04, macos-latest, windows-latest]
 
     steps:
-      - uses: actions/checkout@v2.3.2
+      - name: Checkout
+        uses: actions/checkout@v2.3.2
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Get npm cache directory
-        id: npm-cache
-        run: echo "::set-output name=dir::$(npm config get cache)"
-
-      - uses: actions/cache@v2.1.1
-        with:
-          path: ${{ steps.npm-cache.outputs.dir }}
-          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-node-
-
-      - name: Checkout nodeJS
+      - name: Setup Node.js
         uses: actions/setup-node@v2.1.1
         with:
           node-version: 14
 
-      - name: Install dependencies
-        run: npm i
+      - name: Print CI env variables
+        run: |
+          npx @bahmutov/print-env@v2.1.2 -e USER GITHUB || true
 
-      - name: Cache Cypress binary
+      - id: npm-folder
+        run: |
+          echo '::set-output name=dir::$(npm config get cache)'
+
+      - name: Cache npm
         uses: actions/cache@v2.1.1
         with:
-          path: ~/.cache/Cypress
-          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
+          path: ${{ steps.npm-folder.outputs.dir }}
+          key: ${{ runner.os }}-npm-folder-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
-            cypress-${{ runner.os }}-cypress-
+            ${{ runner.os }}-npm-folder-
 
-      - name: Export
-        run: npm run export
+      - name: Cache node_modules
+        uses: actions/cache@v2.1.1
+        with:
+          path: node_modules
+          key: ${{ runner.os }}-node_modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node_modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
 
-      # killall -9 node (or) pkill node
-      # ps aux | grep -i node | awk '{print $2}' | xargs  kill -9)
-      - name: Start
-        run: npm run static & (sleep 14 && killall -9 node)
-        if: runner.os != 'windows' # for win: cmd "/C TASKKILL /IM node.exe /F"
+      - id: cypress-folder
+        run: |
+          echo '::set-output name=dir::$(cypress cache path)'
+
+      - name: Cache cypress
+        uses: actions/cache@v2.1.1
+        with:
+          path: ${{ steps.cypress-folder.outputs.dir }}
+          # ubuntu: ~/.cache/Cypress
+          # macOS: ~/Library/Caches/Cypress
+          # windows: /AppData/Local/Cypress/Cache
+          key: ${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
+          restore-keys: |
+            ${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
+
+      - name: Install dependencies
+        env:
+          CI: true
+        run: |
+          npm ci
+          npx cypress cache path
+          npx cypress cache list
+          npx cypress verify
+          npx cypress info
+
+      - name: Run build
+        env:
+          CI: true
+        run: |
+          npm run build
+
+      - name: Check installation
+        if: ${{ runner.os == 'linux' }}
+        shell: bash
+        run: |
+          if [ '$(git diff --ignore-space-at-eol | wc -l)' -gt '0' ]; then
+            echo 'Detected uncommitted changes after build.  See status below:'
+            git diff
+            exit 1
+          fi
+
+      - name: Start (linux & osx)
+        if: runner.os != 'windows'
+        run: |
+          npm run static:ci & (sleep 20 && killall -9 node)
+        # or: pkill node
+        # or: ps aux | grep -i node | awk '{print $2}' | xargs  kill -9)
+
+      # - name: Start (windows)
+        # if: runner.os == 'windows'
+        # shell: bash
+        # run: |
+          # npm run static:ci & (sleep 20 && sh -c 'lsof -i :${PORT:-5000} -t' | xargs kill)
+          # or: /C TASKKILL /IM node.exe /F
+          # or: sh -c 'lsof -i :${PORT:-5000} -t | xargs kill
+          # or: netstat -ano | findstr :5000 && taskkill /PID typeyourPIDhere /F
diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -1,76 +1,109 @@
 ---
-name: cypress
+name: Cypress runner
 
 on:
   pull_request:
+    branches:
+      - master
+      - releases/**
     paths-ignore:
       - "**.md"
+
   # push:
-  #   paths-ignore:
-  #     - '**.md'
+    # branches:
+      # - master
+      # - releases/**
+    # paths-ignore:
+      # - "**.md"
 
 jobs:
   test:
     runs-on: ${{ matrix.os }}
-    continue-on-error: false # prevents a workflow run from failing when a job fails
-    timeout-minutes: 12
+    continue-on-error: false # prevents workflows from running when a job fails
+    timeout-minutes: 20
 
     strategy:
-      fail-fast: true # github will cancel all in-progress jobs if any matrix job fails
+      fail-fast: true # cancel all in-progress jobs if any matrix job fails
       matrix:
-        os: [ubuntu-20.04, macos-latest, windows-latest]
-        # machines: [1]
+        os: [ubuntu-20.04, windows-latest, macOS-latest]
 
     steps:
-      - name: Checkout project
+      - name: Checkout
         uses: actions/checkout@v2.3.2
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Get npm cache directory
-        id: npm-cache
-        run: echo "::set-output name=dir::$(npm config get cache)"
-
-      - uses: actions/cache@v2.1.1
-        with:
-          path: ${{ steps.npm-cache.outputs.dir }}
-          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-node-
-      - name: Checkout nodeJS
+      - name: Setup Node.js
         uses: actions/setup-node@v2.1.1
         with:
           node-version: 14
 
-      - name: Install dependencies
+      - name: Print CI env variables
         run: |
-          npm i
+          npx @bahmutov/print-env@v2.1.2 -e USER GITHUB || true
+
+      - id: npm-folder
+        run: |
+          echo '::set-output name=dir::$(npm config get cache)'
+
+      - name: Cache npm
+        uses: actions/cache@v2.1.1
+        with:
+          path: ${{ steps.npm-folder.outputs.dir }}
+          key: ${{ runner.os }}-npm-folder-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-npm-folder-
+
+      - name: Cache node_modules
+        uses: actions/cache@v2.1.1
+        with:
+          path: node_modules
+          key: ${{ runner.os }}-node_modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node_modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
+
+      - id: cypress-folder
+        run: |
+          echo '::set-output name=dir::$(npx cypress cache path)'
+
+      - name: Cache cypress
+        uses: actions/cache@v2.1.1
+        with:
+          path: ${{ steps.cypress-folder.outputs.dir }}
+          # ubuntu: ~/.cache/Cypress
+          # macOS: ~/Library/Caches/Cypress
+          # windows: /AppData/Local/Cypress/Cache
+          key: ${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
+          restore-keys: |
+            ${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
+
+      - name: Install dependencies
+        env:
+          CI: true
+        run: |
+          npm ci
           npx cypress cache path
           npx cypress cache list
           npx cypress verify
           npx cypress info
-      - name: Cache global npm modules
-        uses: actions/cache@v2.1.1
-        with:
-          path: ~/.npm
-          key: ${{ runner.os }}-node-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-node-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
-      - name: Cache cypress
-        uses: actions/cache@v2.1.1
-        with:
-          path: ~/.cache/Cypress
-          key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
-          restore-keys: |
-            cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
-      - name: Cache local npm modules
-        uses: actions/cache@v2.1.1
-        with:
-          path: node_modules
-          key: ${{ runner.os }}-node-modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-node-modules-${{ github.ref }}-
-      - run: npm run test
+
+      - name: Build
+        run: |
+          npm run build
+
+      - name: Diff changes
+        if: ${{ runner.os == 'linux' }}
+        shell: bash
+        run: |
+          if [ '$(git diff --ignore-space-at-eol | wc -l)' -gt '0' ]; then
+            echo 'Detected uncommitted changes after build.  See status below:'
+            git diff
+            exit 1
+          fi
+
+      - name: Run tests
+        run: |
+          npm run test:record:chrome
         env:
           CI: true
           CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
@@ -78,18 +111,7 @@ jobs:
           TERM: xterm
 
       - uses: actions/upload-artifact@v2.1.4
-        if: failure()
-        with:
-          name: screenshots
-          path: cypress/screenshots
-
-      - uses: actions/upload-artifact@v2.1.4
-        with:
-          name: videos
-          path: cypress/videos
-
-      - uses: actions/upload-artifact@v2.1.4
-        if: failure()
+        # if: failure()
         with:
           name: screenshots
           path: cypress/screenshots
